### ISSUE TITLE
needs-restarting handles mirrorlist fetch failure strangely

### ISSUE THREAD

**Issue by FGasper** [rpm-software-management/yum-utils#27]
I recently had a run of `needs-restarting` that exited zero and printed the following on STDOUT:
```
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was
12: Timeout on http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
```
Two requests, then:
1) It seems like this should go to STDERR rather than STDOUT?
2) Shouldn’t `needs-restarting` exit nonzero to indicate that a failure happened?

**Comment by dmnks** [comment]
This is actually `yum` code (not `needs-restarting`) where the error originates from.  I just a made PR based on a similar request that fixes 1 (makes the message go to STDERR), referenced below.

As for 2, this is not the kind of error that alone should make yum fail.  There are multiple ways to specify the urls for a repo: `baseurl`, `mirrorlist` and `metalink`, so if one fails, there may still be some urls left to work with. Only if no urls are left will yum fail with the exit code 1, which doesn't seem to be your case (the repo that failed probably also has a `baseurl` defined in its config file).

Feel free to reopen this issue if you experience 2 even with `mirrorlist` being the only source of urls. Thanks!
