### ISSUE TITLE
Increase the maximum repo priority value for yum-plugin-priorities

### ISSUE THREAD

**Issue by gdubicki** [rpm-software-management/yum-utils#29]
As https://github.com/rpm-software-management/yum-utils/tree/master/plugins/priorities states the current default priority for a repo is 99.

This is bad because it's also the lowest possible priority (maximum value).

So if you want to add a new repo to a bunch of repos without priority being set, and you want this new repo to have lower priority, you can't.

Changing the default to 50 would be a very breaking change so I don't propose that.

Instead let's increase the maximum value of this setting to, let's say, round 256. ;) This way nothing will break and you will be able to easily do what I proposed above - you would just add this single new repo with priority > 99.

**Comment by james-antill** [comment]
> This is bad because it's also the lowest possible priority (maximum value).

Where is the check that does this? The code uses:

https://github.com/rpm-software-management/yum-utils/blob/master/plugins/priorities/priorities.py#L71

     config.RepoConf.priority = config.IntOption(99)

...which is defined as:

https://github.com/rpm-software-management/yum/blob/master/yum/config.py#L292

      def __init__(self, default=None, range_min=None, range_max=None):

...so range_max is None, and the checking code is:

https://github.com/rpm-software-management/yum/blob/master/yum/config.py#L309

          if self._range_max is not None and val > self._range_max:
              raise ValueError('out of range integer value')

**Comment by gdubicki** [comment]
I got an error from something that told me that values 1-99 are allowed but I can't check what that was right now..

**Comment by dmnks** [comment]
It seems that James is right in that there really isn't any piece of code that would enforce the 1-99 range (the 99 in `IntOption(99)` just sets the default value, see the snippet above).

```
$ git grep 99
README:priority for repositories is 99. The repositories with the lowest
priorities.py:# priority for repositories is 99. The repositories with the lowest
priorities.py:        config.RepoConf.priority = config.IntOption(99)
priorities.py:        conduit.registerOpt('priority', PLUG_OPT_INT, PLUG_OPT_WHERE_REPO, 99)
```

**Comment by gdubicki** [comment]
It was puppet that limited me to 1-99. It already has a ticket for fixing it: https://tickets.puppetlabs.com/browse/PUP-4678 . We can close it here, thank you for clarifications @james-antill & @dmnks .
