### ISSUE TITLE
Allow rebootpkgs to be configurable.

### ISSUE THREAD

**Issue by tkimball83** [rpm-software-management/yum-utils#36]
I opened an issue here as well => https://github.com/stdevel/yum-plugin-needs-restarting

The title says it all really.

For example, I'm using the mainline kernels from the elrepo-kernel repository, and the package names differ.  They use kernel-lt and kernel-ml to not conflict with the base operating system.

Therefore, allowing rebootpkgs to be configurable via /etc/yum/pluginconf.d/needsrestarting.conf would be ideal so additional packages can be defined.

The end result I'm looking for is this:
```
--- /usr/bin/needs-restarting	2017-08-11 10:23:16.000000000 +0000
+++ needs-restarting	2017-12-13 23:12:50.154531568 +0000
@@ -50,8 +50,8 @@

 # For which package updates we should recommend a reboot
 # Taken from https://access.redhat.com/solutions/27943
-REBOOTPKGS = ['kernel', 'glibc', 'linux-firmware', 'systemd', 'udev',
-              'openssl-libs', 'gnutls', 'dbus']
+REBOOTPKGS = ['kernel', 'kernel-lt', 'kernel-ml', 'glibc', 'linux-firmware',
+              'systemd', 'udev', 'openssl-libs', 'gnutls', 'dbus']

 def parseargs(args):
     usage = """
```

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.

**Comment by ocstx** [comment]
This has not been solved in dnf.
the problem remains in centos8

**Comment by dmnks** [comment]
@ocstx, true: https://github.com/rpm-software-management/dnf-plugins-core/blob/af1a0550e79f719ca1aed518c00df066ae79df9d/plugins/needs_restarting.py#L40

Please file an issue in the dnf-plugins-core repo.

**Comment by ocstx** [comment]
thank you for your comment!
unofrtunately the tab issues is not visible to me here:
https://github.com/rpm-software-management/dnf-plugins-core
can you?
thank you

**Comment by dmnks** [comment]
Oh. You're actually right, there's no Issues tab any more :) The reason is that the team prefers the Red Hat Bugzilla instance for bug reports and feature requests.

Please use this link to report one (select "dnf-plugins-core" as the component): https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora

EDIT: Also see this: https://github.com/rpm-software-management/dnf-plugins-core#bug-reporting-etc

**Comment by ocstx** [comment]
DONE!
https://bugzilla.redhat.com/show_bug.cgi?id=1901921

**Comment by dmnks** [comment]
Thanks!

**Comment by ocstx** [comment]
According to this:
https://bugzilla.redhat.com/show_bug.cgi?id=1901921
it has been solved.
from the previous link:
Example: echo "packagename" > /etc/dnf/plugins/needs-restarting.d/packagename.conf
