### ISSUE TITLE
reposync seemingly doesn't use 'gpgcheck' from config file

### ISSUE THREAD

**Issue by ajf** [rpm-software-management/yum-utils#37]
Given a configuration file:

```
[main]
reposdir     = /etc/reposync/yum.repos.el6-x86_64.d
persistdir   = /srv/reposync/.persist/el6-x86_64
cachedir     = /srv/reposync/.cache/el6-x86_64
keepcache    = 0
debuglevel   = 2
errorlevel   = 2
logfile      = /var/log/reposync.log
tolerant     = 1
exactarch    = 1
obsoletes    = 1
gpgcheck     = 1
plugins      = 1

[centos-6.9-updates]
name=CentOS 6.9 Updates x86_64
baseurl=http://mirror.centos.org/centos/6.9/updates/x86_64/
enabled=1
gpgcheck=1
gpgkey=file:///srv/reposync/el6-x86_64/centos-6.9-updates.gpg
description=CentOS 6.9 Updates x86_64
```

It does not appear that the `gpgcheck` argument is used, and `--gpgcheck` needs to be passed on the reposync command line (even though it's specified in the configuration file).  This makes it impossible to use reposync to sync an entire group, some which use gpgcheck and some that dont.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
