### ISSUE TITLE
reposync exit status

### ISSUE THREAD

**Issue by arodd** [rpm-software-management/yum-utils#38]
The exit status for reposync could change depending on whether packages failed the gpgcheck and were removed but the rest of the sync was otherwise successful vs. the sync failing for some reason.  Instead of 1 for everything, gpg failure could use a higher number so that you could 
 still determine if the sync was successful even though certain packages may have not been signed or didn't validate.  Sometimes upstream repos have missing signatures or repo rpm's that aren't signed so that they can distribute the key/repo path and so these could be removed but the sync would have otherwise completed successfully.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
