### ISSUE TITLE
fastestmirror plugin ignores proxy settings

### ISSUE THREAD

**Issue by smil2k** [rpm-software-management/yum-utils#39]
In case of running with "fastersmirror" plugin behind proxy, the plugin stuck at resolving/connecting to addresses, because it does not use the configured proxy settings.

At least it should skip itself in case of proxy present.

**Comment by aneagoe** [comment]
In [this](https://bugzilla.redhat.com/show_bug.cgi?id=505405) bug there is a proposed fix attached and someone confirms that some "basic" functionality for supporting proxy settings was present in yum-plugin-fastestmirror-1.1.24-2. However, there's no direct evidence (that I could find) in the github repo. Looks like this was never actually implemented. For the time being, people have to resort to disabling the plugin if proxy is configured/required. +1 for having the proxy support in the plugin or as suggested a way of skipping if proxy is configured for yum.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
