### ISSUE TITLE
keys plugin should provide option to import key

### ISSUE THREAD

**Issue by dcode** [rpm-software-management/yum-utils#40]
When provisioning systems, I like to ensure all keys are imported as trusted using automation. I use ansible for this, but this issue holds true for bash or anything else. For RPM signatures, this is easy. Do the equivalent of `rpm --import` with the GPG key. However, for `repo_gpgcheck`, it appears the only way to do this is to do the work around that is suggested on several mailing lists, StackExchange, and others: 
```
yum -q makecache -y --disablerepo='*' --enablerepo='repoid'
```
This isn't nearly as nice as `rpm --import`, as it requires the system is online at the time and it downloads the metadata of the repo. When I'm provisioning systems for VM templates, I end up removing the cached metadata anyway.

I'd like to see a `yum keys-import /path/to/gpg/key.pub` command to take care of this offline.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
