### ISSUE TITLE
reposync fails to sync (if file already exists with same filename)

### ISSUE THREAD

**Issue by saranathak** [rpm-software-management/yum-utils#45]
having a weird issue when the reposync tries to sync (updated)remote rpm file which already exists locally. Apparently remote repo, is being updated with the same filename (no versioning), and reposync fails with "[Errno 256] No more mirrors to try." . Looks like there is bug being tracked https://bugzilla.redhat.com/show_bug.cgi?id=1399235 and also bug # 13775514

Any workarounds or anyone willing to throw more light on this.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
