### ISSUE TITLE
yum-config-manager does not sanitize `@` when adding repo from the URL

### ISSUE THREAD

**Issue by bbaja42** [rpm-software-management/yum-utils#48]
To reproduce

[root@c79bfb7185b1 yum.repos.d]# yum-config-manager --add-repo "https://user:pass@website.com"
[root@c79bfb7185b1 yum.repos.d]# yum search bla
Bad id for repo: pass@website.com, byte = @ 4
From looking at the code,
yum/yum/misc.py

Line 1252 in 1222f37

 allowed_chars = string.ascii_letters + string.digits + '-_.:' 

Checks what is valid repo_id
def validate_repoid(repoid):
    """Return the first invalid char found in the repoid, or None."""
    allowed_chars = string.ascii_letters + string.digits + '-_.:'
    for char in repoid:
        if char not in allowed_chars:
            return char
    else:
        return None
and sanitization is done in http://yum.baseurl.org/gitweb?p=yum-utils.git;a=blob;f=yum-config-manager.py;h=380a54fd89b8d2f1afc96020be20d231733b838b;hb=HEAD#l19

So IMHO, either validation should allow @, or sanitization should remove all not ascii chars, other than -_:

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
