### ISSUE TITLE
reposync performance issue between el6 and el7

### ISSUE THREAD

**Issue by schplat** [rpm-software-management/yum-utils#51]
Can someone explain to me the difference between the version of reposync on el6 and el7 such that we see this kind of difference between the identical commands run on each:

EL6:
```
$ time sudo /usr/bin/reposync -l -m -d --config=/var/www/cobbler/repo_mirror/datadog/.origin/datadog.repo --repoid=datadog --download_path=/var/www/cobbler/repo_mirror -a x86_64
...
real	0m0.272s
user	0m0.204s
sys	0m0.064s
```

EL7:
```
$ time sudo /usr/bin/reposync -l -m -d --config=/var/www/cobbler/repo_mirror/datadog/.origin/datadog.repo --repoid=datadog --download_path=/var/www/cobbler/repo_mirror -a x86_64
...
real	1m0.591s
user	0m11.852s
sys	0m2.382s
```

I'll also note, that both systems have the repo download and up to date.  It seems that the EL7 reposync wants to read through each an every single package serially, but do nothing with it?  At least that's what I glean from strace, as it does open, read, close, and doesn't actually pass off the files to any other process or any other operations are done.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.

**Comment by clayne** [comment]
@schplat FYI: to followup on this 6 year old question in case it's beneficial to others, the change in behavior between 6->7 was that reposync started doing full package checksums rather than just mtime+size comparisons. The behavior was then replicated in the python wrapper plugin for reposync when DNF started to be used rather than yum.
