### ISSUE TITLE
needs-restarting should indicate errno when open(/proc/$pid/smaps) fails

### ISSUE THREAD

**Issue by FGasper** [rpm-software-management/yum-utils#52]
We recently saw this when running needs-restarting under virtualization:
```
Could not open /proc/16926/smaps
```
I’m submitting a PR that adds the error description.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
