### ISSUE TITLE
[merge-conf] should have an action option calling yum -y

### ISSUE THREAD

**Issue by tuxmaster5000** [rpm-software-management/yum-utils#55]
Current when yum called via  the -y option than the merge-conf plug-in is disabled.
For automatic run, there should be an option to set the behaviour instant an simple "Do nothing"
Scenario:
call yum update -y
let puppet or something like this run.
Now, puppet don't use the new config.

My suggestion will be the parameter --merge-conf-defaultm which can be set to i, so the config of the new package is used.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
