### ISSUE TITLE
Create files with instructions for setuptools to create a wheel

### ISSUE THREAD

**Issue by KOLANICH** [rpm-software-management/yum-utils#59]
I mean `setup.cfg` and `setup.py`.

**Comment by fruch** [comment]
also uploading to pypi, would be very nice.
my exact use case is using yumdownloader while in alpine

**Comment by KOLANICH** [comment]
>also uploading to pypi, would be very nice.

Considered to be an antipattern. Just install from git.

**Comment by fruch** [comment]
uploading packages to pypi is an antipattern ?!?! 
everyday you learn something new....

**Comment by KOLANICH** [comment]
Yes. Some malware has been spotted there. Sources in git repos are at leasy visible to the contributors. Sources in zip archives on pypi are looked by almost noone.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
