### ISSUE TITLE
help~   Why " yumdownloader source " can't find src.rpm ?

### ISSUE THREAD

**Issue by yifengyou** [rpm-software-management/yum-utils#61]
![image](https://user-images.githubusercontent.com/19882390/71439320-2c1b7100-2734-11ea-9253-3a57271ec22b.png)
![image](https://user-images.githubusercontent.com/19882390/71439336-363d6f80-2734-11ea-81b7-54a8f306161a.png)

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
