### ISSUE TITLE
needs-restarting.py for python3?

### ISSUE THREAD

**Issue by asimzeeshan** [rpm-software-management/yum-utils#64]
Thank you for the awesome piece of code
[needs-restarting.py](https://github.com/rpm-software-management/yum-utils/blob/master/needs-restarting.py) works fine on centos/rhel servers running python but it doesn't on python3 (tried changing the shebang but it wont help)

The error received is
```
root@rhel:~# ~/needs-restarting.py -r
  File "/root/needs-restarting.py", line 95
    except (IOError, OSError), e:
                             ^
SyntaxError: invalid syntax
```

can you please help me fix this?

**Comment by lukash** [comment]
Hello, yum-utils is not ported to Python 3, it has been superseded by the needs-restarting plugin of dnf-plugins-core on modern systems (source: https://github.com/rpm-software-management/dnf-plugins-core/blob/master/plugins/needs_restarting.py). Assuming you use dnf, not yum. yum-utils won't be ported to Python 3, if you use yum, you're stuck with Python 2 here...
