### ISSUE TITLE
reposync N newest packages?

### ISSUE THREAD

**Issue by earsdown** [rpm-software-management/yum-utils#9]
I'm trying to figure out a way to sync a remote yum repository so that I can control how many previous versions get downloaded. Right now reposync only supports **all** or **newest-only**. The use case is to keep a few older versions in my local repo just in case I need to roll-back quickly (and not have to rely on a cached version in /var/cache/yum).

My current workaround is to run `reposync --newest-only` (and without `--delete`) then as a separate step use `repomanage` to purge really old packages. I call this a workaround because I actually want the _N_ newest packages from the **remote** repository, regardless of I've downloaded in the past (i.e. I don't want to create a situation where a release was missed).

Any ideas? I'm still a novice in python but with some direction and guidance I'm willing to have a go at implementing this enhancement.

FYI: I'm currently forced to mirror an entire 37G repo, even though I only need about 1G worth of packages. To make things worse, that 37G repo gets sync'd to a bunch of S3 buckets, because client machines get their packages from those S3 buckets (via the yum S3 plugin) in stages (i.e. "latest", "test", "prod", etc). So yeah, there's definitely a cost-saving incentive to get this feature implemented.

**Comment by james-antill** [comment]
From python all the packages will sort by name and then by version (oldest to newest). So something like this::

```
for pkg in yb.pkgSack.returnPackages():
    pkgs.setdefault(pkg.name, []).append(pkg)
for name in pkgs:
    newestN = sorted(pkgs[name])[-N:]
    pkgs[name] = newestN
```

**Comment by patsevanton** [comment]
Somebody add sync N newest packages to reposync. Please.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.

**Comment by James-E-A** [comment]
> Please consider migrating to DNF which is the successor of YUM

Sadly, **this bug is still present**: `dnf reposync` does not recognize DNF's `--latest-limit` option.

However, [the newer code](https://github.com/rpm-software-management/dnf-plugins-core/blob/4.0.2.2/plugins/reposync.py#L161) looks suspiciously similar to that which @Nihlus fixed; I'll try my hand at translating the patch
